name: hello-world
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone-down
        uses: actions/checkout@v3   
      - name: Build application
        run: ./ci/build-app.sh
      - name: upload builded app
        uses: actions/upload-artifact@v3
        with:
          name: compiled app
          path: .
  Test: 
    needs: [Build]
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Download compiled app
        uses: actions/download-artifact@v3
        with:
          name: compiled app
          path: .
      - name: Test
        run: chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh
